# WARNING:
# I changed the default kitty modifier key.
# Currently it is set to Ctrl+Super.
# 
# If you prefer the default Ctrl+Shift instead:
# 1. Comment out the line below (add a # in front of it)
kitty_mod ctrl+super

# 2. Uncomment the line below  (Ctrl+Shift)

# kitty_mod ctrl+shift



tab_bar_edge bottom
tab_bar_min_tabs 1
tab_title_template 😸{title}


hide_window_decorations no
tab_bar_style custom
tab_bar_min_tabs 1

allow_remote_control yes

show_hyperlink_targets yes
underline_hyperlinks hover
copy_on_select yes
enable_audio_bell no
bell_on_tab "🔔 "
allow_remote_control yes
map kitty_mod+escape kitty_shell window

font_family     FiraCode Nerd Font Mono
font_size       14.0
enabled_layouts Tall, *
window_margin_width     10

window_border_width     1pt
active_border_color     #44ffff


include open-actions.conf
include current-theme.conf
